### ISSUE TITLE
BMD - Textures without coordinate generator

### ISSUE THREAD

**Issue by Wexos** [riidefi/RiiStudio#11]
I attached a BMD file from MKDD. It has a single material, which contains two textures but only a single texture coordinate generator. In the samplers tab it says "cannot edit: source data is invalid!". In the second TEV stage it says "TODO: TexCoord != TexMap: Not valid". The two textures use the same generator for both textures in both TEV stages.

[signal1.zip](https://github.com/riidefi/RiiStudio/files/5759421/signal1.zip)

**Comment by riidefi** [comment]
I've thought this over a bit, and I think the best solution is to split shared texgens into unique ones after the file is read. Then on write, an additional optimization step can merge duplicate texgens. This would also improve the output of BRRES files.

**Comment by riidefi** [comment]
Note: This was the same issue affecting Galaxy's `bombtimeattackplanet.bdl`
With the latest commits, this should be entirely fixed.
