### ISSUE TITLE
Certain transformed textures look different in riistudio than they do exported/in-game

### ISSUE THREAD

**Issue by islender** [riidefi/RiiStudio#12]
I am trying to align a texture a certain way in Riistudio using the functions: Rotate, Scale and Transform. When I noticed my texture was perfectly aligned, I exported it. I then tried it in-game, but the texture was actually transformed a little different than how it was in Riistudio, which doesn't make sense. It seemed like the X and Y axis of the transformation was flipped, where X became Y vice versa, but I cannot confirm this for sure. I can not provide images as an example. However, this is easily recreatable. I reopened the exported model in Riistudio, and it still looked correctly aligned, and just for good measure exported and tested it again, but it was still bugged.

Edit: The initial model import was a BDL

Edit 2: I tried both Alpha 5.0 and 4.0, error persists on both

**Comment by riidefi** [comment]
Thanks for pointing this out. I'll look into it soon.

(This is probably a bug with [librii::mtx](https://github.com/riidefi/RiiStudio/blob/master/source/librii/mtx/TexMtx.hpp))

**Comment by riidefi** [comment]
This should be fixed in the latest release (available through the auto updater). Let me know if it fixed it for you!

**Comment by islender** [comment]
Will look into it, thanks! I'll report back.

**Comment by islender** [comment]
The issue is fixed. Thanks!
