### ISSUE TITLE
Transform Model not saved after changing

### ISSUE THREAD

**Issue by islender** [riidefi/RiiStudio#13]
If you change the Transform Model to something other than default then hit save, when the file is relaunched, that property is set back to default.

Tried opening the after-it-was-saved model in j3dview, and I can confirm that the property was not saved.

The initial model import was BDL, also I used Riistudio Alpha 5.1.

**Comment by riidefi** [comment]
Those options are mostly for BRRES. BMD only supports "Basic" and "Maya".

Ideally those would be hidden in BMD mode.

**Comment by islender** [comment]
Oh, apologies. Didn't realise those weren't supported in BMD format.

I suggest adding a sort of prompt inside Riistudio which warns you if the setting is not supported.

**Comment by riidefi** [comment]
No reason to apologize. I'll fix it now.

**Comment by islender** [comment]
Oh amazing, thanks!
