### ISSUE TITLE
Crash bug when selecting the "Windows" section of the toolbar.

### ISSUE THREAD

**Issue by Brawlboxgaming** [riidefi/RiiStudio#20]
Just putting this here as a reminder but I'm fairly sure it's known.
![image](https://user-images.githubusercontent.com/71042104/113485105-e2c3e080-94a3-11eb-9cf2-a3f2cbb6fe59.png)

**Comment by riidefi** [comment]
I'm aware of it. It's fixed in the main branch. You can grab a development build [here](https://github.com/riidefi/RiiStudio/suites/2401299962/artifacts/51084317).
