### ISSUE TITLE
Removes "Unused" Textures upon saving.

### ISSUE THREAD

**Issue by gayfrogog** [riidefi/RiiStudio#22]
Saving a BMD/BDL with textures not being used by any materials on the model will remove said textures. This breaks multiple animations and causes crashes when replacing character models in Super Mario Sunshine and Super Mario Galaxy for example.
Attached is a zip containing two files, one being the original Mario.bdl file, and the other a Mario.bmd saved using RiiStudio. Unsure if this is intentional or not, but the issue still stands.
[Mario.zip](https://github.com/riidefi/RiiStudio/files/7021416/Mario.zip)

**Comment by riidefi** [comment]
This problem is a bit more challenging under-the-hood than it might appear. I'll need to think of how I want to approach it.

**Comment by riidefi** [comment]
Addressed in 7d3a769
