### ISSUE TITLE
Ability to add textures to a BMD that has none

### ISSUE THREAD

**Issue by JoshuaMKW** [riidefi/RiiStudio#26]
When a BMD has no textures in RiiStudio, it is impossible (or at least very obfuscated) to add textures since the "Textures" group doesn't exist in the data hierarchy.

Ideally, you could still add a texture which would cause the group to reappear, or explicitly add the group to the data hierarchy as an empty default.

**Comment by riidefi** [comment]
Addressed in 314c844 and 78baddd.
