### ISSUE TITLE
luigi_circuit.brres Automatically Loads When Riistudio Opens

### ISSUE THREAD

**Issue by Gabbo089** [riidefi/RiiStudio#29]
When Riistudio opens, it automatically loads the importer pop-up.
![riis](https://user-images.githubusercontent.com/74122269/202878656-8d1a4583-81fe-4873-93f9-2e59c45fe20a.PNG)
After that, luigi_circuit.brres loads into the editor.
![rii2](https://user-images.githubusercontent.com/74122269/202878729-f125828c-b720-4061-a9d2-4b6f960c1175.PNG)
Just to be clear, I don't have that file saved into my pc.

**Comment by JoshuaMKW** [comment]
Is this the web version? For that at least I always assumed this was an introduction feature to allow quick editing.

**Comment by Gabbo089** [comment]
Indeed it is. 
I assumed that it was an introduction feature too, but the Importer pop-up makes me question it.
