### ISSUE TITLE
Can no longer open SZS files

### ISSUE THREAD

**Issue by LemonadeSnake** [riidefi/RiiStudio#34]
Whenever I try to open a .szs file it says 'Level Editor: < unknown >'
![image](https://user-images.githubusercontent.com/78671572/224785569-69cbf0ea-bc04-400a-ae12-5792e4b51cca.png)
![image](https://user-images.githubusercontent.com/78671572/224785962-5c0b4b8e-5db1-4884-9222-bddd81848a7f.png)
![image](https://user-images.githubusercontent.com/78671572/224786005-91d4dc8c-8fae-4aad-8922-1c4609df4d48.png)

**Comment by riidefi** [comment]
This should be fixed in Alpha-5.10.4
