### ISSUE TITLE
BDL texture matrix rotation not saved correctly

### ISSUE THREAD

**Issue by AllocatorMK** [riidefi/RiiStudio#4]
When saving a BDL file, the rotation in a texture matrix is converted to radians.

![Original](https://user-images.githubusercontent.com/69111085/89898467-13879a80-dbe1-11ea-9507-fe4fb66820f4.png)
![Saved](https://user-images.githubusercontent.com/69111085/89898475-16828b00-dbe1-11ea-97b9-34ee269fd999.png)

**Comment by riidefi** [comment]
Fixed it! The update should be live now.
