### ISSUE TITLE
Unable to select a different Sampler ID with the same name in the 'Stage' tab

### ISSUE THREAD

**Issue by GerasSB** [riidefi/RiiStudio#42]
If there's a texture that's indexed twice, you're only able to select the first one in the `Stage` tab.

### Explanation
Here's a material with two samplers. Both samplers share the same name and texture, but have different indexes as they were set up separately within `texheaders.json`. You can edit them individually as expected.

![image](https://user-images.githubusercontent.com/19808950/233215550-c4d2dbbe-1978-4ac9-9e40-337c1695aa5e.png)

When going to the `Stage` tab, however, you can only select the one with index [0]. Clicking on any other with the same name does nothing.

![image](https://user-images.githubusercontent.com/19808950/233215785-9c6de6f9-a5ad-4832-b2f9-07fa3993601f.png)

**Comment by riidefi** [comment]
Thanks for the reports. This should be fixed along with #43 and #41. Will release a new version momentarily.
