### ISSUE TITLE
None-8 bit color formats not displayed correctly

### ISSUE THREAD

**Issue by Wexos** [riidefi/RiiStudio#6]
For BMD, RGBA4, RGBA6 and RGB565 are not displayed correctly (way too dark). I have verified RGBA4 in Dolphin.

[Samples.zip](https://github.com/riidefi/RiiStudio/files/5562764/Samples.zip)

![RGBA8](https://user-images.githubusercontent.com/29820962/99586563-339cd600-29e8-11eb-925e-b65f0aa197c0.png)
![RGB565](https://user-images.githubusercontent.com/29820962/99586595-3c8da780-29e8-11eb-9bfc-3ac85e2d6ac9.png)
![RGBA4](https://user-images.githubusercontent.com/29820962/99586619-444d4c00-29e8-11eb-9de7-449389e684e5.png)

**Comment by riidefi** [comment]
Fixed with the latest commit. It won't be visible on github.io immediately, but should be there soon in the next release.
